### ISSUE TITLE
Add Meta Characters

### ISSUE THREAD

**Issue by fstermann** [fstermann/ezr#2]
Add the various meta characters as a subclass of the base pattern #1 

# Meta Characters
- [x] `.` Dot
- [x] `^` Caret. Beginning of string
- [x] `$` Dollar. End of string
- [ ] `\A` Beginning of string
- [x] `\b` Word boundary
- [x] `\B` Non-word boundary
- [x] `\d` Digit
- [x] `\s` Whitespace character
- [x] `\S` Non-whitespace character
- [x] `\w` Alphanumeric "word" character (letter or digit)
- [x] `\W` Non-alphanumeric
- [ ] `\z` End of string
